### ISSUE TITLE
Response data: HTTP Token: Access denied. Error thrown by XCode after running code.

### ISSUE THREAD

**Issue by ihemantd** [conferencesapp/rubyconferences-ios#16]
While running this project in XCode
`func getConferencesFromApi()` is throwing error
`Request failed with error: Error Domain=NSCocoaErrorDomain Code=3840`
`Response data: HTTP Token: Access denied.`

For `Alamofire.request(.GET, "\(apiUrl)/v1/conferences?tags=ruby", headers: headers)`
It successfully returns data but exception is thrown in `func processResults(data: NSArray)`

Please help me running this project with  `\(apiUrl)//v2`

Thanks,

**Comment by arunagw** [comment]
Hey @ihemantd Thanks for trying this out. 

Unfortunately the version v2 is restricted with token. But If you want to run this and knows a bit of ruby you can setup the server part easily on local or server. 

Here is repo https://github.com/conferencesapp/rubyconferences-server

I can also share access token for staging server which you can use temporary fetch data.

**Comment by ihemantd** [comment]
@arunagw I think access token for staging server would be helpful 
for me because, I don't have experience setting up server. I have experience
of standalone desktop application.
What will be my API URL of staging server ? 
In case if you need my email id for sharing access token - its hmavachi at gmail.com

I will try setting local server in future, if needed.

Thanks for the help.

**Comment by arunagw** [comment]
Email sent. thanks.

**Comment by ihemantd** [comment]
Received it. Thank you very much.

**Comment by arunagw** [comment]
@ihemantd Now I have made a change that will require no API token to access `v2` endpoint.
