### ISSUE TITLE
Create an event in calendar when click on calendar icon on conference view screen

### ISSUE THREAD

**Issue by raysrashmi** [conferencesapp/rubyconferences-ios#25]

**Comment by ihemantd** [comment]
I am working on this feature.

**Comment by arunagw** [comment]
@ihemantd great thanks! Let us know if you need any help.

**Comment by raysrashmi** [comment]
:+1:

**Comment by ihemantd** [comment]
Yes I have a question.
1. Any other possible date formats I need to handle, other than something like November 15-26, 2015  and  November 15, 2015 ?

**Comment by arunagw** [comment]
I think we do have `start_date` and `end_date` in API and those are the format we are going to stick with for now. The mixed format coming from server is mostly to just display on screen so I think using that for Calendar is not a good idea.

**Comment by ihemantd** [comment]
@arunagw  Thank for the clarification !. Since end_date was not accessed / stored anywhere I though I would need to use "when" property to extract the information.

**Comment by ihemantd** [comment]
Another question 
If same event already exists in calendar, should I handle deleting event too.
If yes, how do we plan to indicate user that event is already present in calendar. Should we change icon to indicate that ?

**Comment by arunagw** [comment]
@ihemantd yes. I think we are not using `start_date` and `end_date` but you can use it. It was easy to just render `when` from server to not do too much calculation on device.

I am not sure it's possible to detect with name in Calendar and also a good idea.. because there will be no unique thing we can store Calendar. I think it's fine to have a tap and ask for Calendar and then show the preview and let them add. May be I am missing something.

**Comment by ihemantd** [comment]
There are two ways to detect event.
1. Querying EKEventStore with predicateForEventsWithStartDate. It will match conference title with event title.

2. Using eventWithIdentifier.  At the time of creating / storing event, Event store gives us eventStoreIdentifier but we need to store it in database to use it later.

Using Event store we don't need to invoke separate calendar application. 
We will ask permission and add event programmatically.

**Comment by arunagw** [comment]
So if we store `eventStoreIdentifier` in local database it will be fine I think. As it will be per device.

**Comment by ihemantd** [comment]
Ok.

**Comment by ihemantd** [comment]
I need help with storing `calendar event id` in database.
Creating and removing calendar event is done but I am stuck with storing event id in database.
I have added new field to `class Conference`,  it is saved correctly in database but
when application is re-run, it re-fetches all conferences from server, it flushes all stored calendar events ids.

Specifically this function
`func processResults(data: NSArray)`
and this call to be exact
`realm.create(Conference.self, value: conf, update: true)`

Only one approach I can think is before `realm.create(Conference.self, value: conf, update: true)`
call, remove stored calendar event id from database using conference id, and assign to new conference
object created.

Is it a correct approach ?
Should I create different class for storing conference id and calendar event id ?

**Comment by arunagw** [comment]
I think having a new class stored just locally seems fine to me. So it become per device and per conference.

**Comment by raysrashmi** [comment]
https://github.com/conferencesapp/rubyconferences-ios/pull/36
